# Generated by Django 4.0.3 on 2022-04-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_superuser',
        ),
    ]
